package info.cubanmusic.cubanmusicapi.model

import java.io.Serializable
import java.util.*

data class PersonDto(
    var id: UUID? = UUID.randomUUID(),
    var name: String? = null,
    var biography: String? = null,
    var alias: String? = null,
    var email: String? = null,
    var website: String? = null,
    var activeSince: Int? = null,
    var activeUntil: Int? = null,
    var isniCode: String? = null,
    var spotify: String? = null,
    var appleMusic: String? = null,
    var soundCloud: String? = null,
    var deezer: String? = null,
    var youtube: String? = null,
    var instagram: String? = null,
    var viberate: String? = null,
    var facebook: String? = null,
    var twitter: String? = null,
    var tiktok: String? = null,
    var reverbNation: String? = null,
    var libOfCongress: String? = null,
    var nationality: String? = null,
    var schoolId: UUID? = null,
    var recordLabelId: UUID? = null,
    var organizationId: UUID? = null,
    var additionalNames: MutableSet<String> = mutableSetOf(),
    var relatedArtists: MutableSet<String> = mutableSetOf(),
    var birthDate: String? = null,
    var deathDate: String? = null,
    var gender: Gender = Gender.OTHER,
    var birthPlaceId: UUID? = null,
    var deathPlaceId: UUID? = null,
    var residencePlaceId: UUID? = null,
    var memberOfId: UUID? = null,
    var jobTitleId: UUID? = null,
    var jobRoles: MutableSet<String> = mutableSetOf(),
    var instrumentsIds: MutableSet<UUID> = mutableSetOf(),
    var genresIds: MutableSet<UUID> = mutableSetOf(),
    var albumsIds: MutableSet<UUID> = mutableSetOf(),
    var awardsIds: MutableSet<UUID> = mutableSetOf(),
    var imageFile: ImageFileDto? = null,
) : Serializable
